[skip-ci] Getting closer with release

diff --git a/.github/workflows/release-test.yml b/.github/workflows/release-test.yml
--- a/.github/workflows/release-test.yml
+++ b/.github/workflows/release-test.yml
@@ -1,11 +1,13 @@
 name: Testing plugin release
+
 on:
   workflow_dispatch:
     inputs:
-      releaseVersion:
-        decription: "Release version"
+      bumpVersion:
+        decription: |
+          Bump to this version after release.
+          If left empty will bump revision only
         required: false
-
 
 jobs:
   releasePlugin:
@@ -19,11 +21,22 @@ jobs:
     - uses: leafo/gh-actions-luarocks@v4
 
     - name: Install locally
-      env:
-        PLUGIN_RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
       run: |
         SPEC_FILE=$(ls kong-plugin-tag-executor-*.rockspec)
+        alias plug_version='luarocks show kong-plugin-tag-executor | grep kong-plugin-tag-executor | head -n 1 | cut -d" " -f 2'
         luarocks install --local $SPEC_FILE
-        luarocks show kong-plugin-tag-executor
-        luarocks new_version $SPEC_FILE $PLUGIN_RELEASE_VERSION
+    - name: Release plugin
+      run: |
+        RELEASE_VERSION=$(plug_version)
+        luarocks upload --api-key aahaha $SPEC_FILE || echo "fail"
+    - name: Bump version
+      env:
+        INPUT_VERSION: ${{ github.event.inputs.releaseVersion }}
+      run:
+        luarocks new_version $SPEC_FILE $INPUT_VERSION
         rm $SPEC_FILE
+        SPEC_FILE=$(ls kong-plugin-tag-executor-*.rockspec)
+        luarocks install --local $SPEC_FILE
+        NEW_VERSION=$(plug_version)
+        echo 'New version: $NEW_VERSION'
+        ls -la
